version: '3.9'

services:
  vault-server:
    image: vault:1.13.2
    ports:
      - '8200:8200'
    environment:
      VAULT_ADDR: 'http://0.0.0.0:8200'
      VAULT_DEV_ROOT_TOKEN_ID: 'vault-plaintext-root-token'
